env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_TRIPLET: x64-windows

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg $env:VCPKG_ROOT
          & "$env:VCPKG_ROOT\bootstrap-vcpkg.bat" -disableMetrics
          echo "$env:VCPKG_ROOT\vcpkg.exe" >> $env:GITHUB_PATH

      - name: Install dependencies
        run: vcpkg install librdkafka --triplet $env:VCPKG_TRIPLET

      - name: Check RdKafka files
        run: ls $env:VCPKG_ROOT/installed/$env:VCPKG_TRIPLET/share/rdkafka

      - name: Configure CMake
        run: |
          cmake -B build -S . -A x64 `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=$env:VCPKG_TRIPLET

      - name: Build
        run: cmake --build build --config Release