name: C++ CI

on: [push, pull_request]

env:
  VCPKG_DIR: ./vcpkg
  VCPKG_TRIPLET: x64-windows

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: vcpkg install librdkafka --triplet $env:VCPKG_TRIPLET

      - name: Check RdKafka config files new
        run: ls C:/vcpkg/installed/$env:VCPKG_TRIPLET/share/rdkafka

      - name: Configure CMake
        run: |
          cmake -B build -S . -A x64 `
            -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build the project
        run: cmake --build build --config Release